# Generated by Django 5.1.2 on 2024-10-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('day', models.CharField(max_length=255)),
            ],
        ),
    ]
