# Generated by Django 5.1.2 on 2024-10-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('day', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=355, null=True)),
                ('date', models.DateTimeField()),
                ('calendar_id', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='year',
            field=models.PositiveIntegerField(default=1997),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
